### ISSUE TITLE
Error due to special characters

### ISSUE THREAD

**Issue by patrickbuff** [u01jmg3/ics-parser#110]
Since one week I become this error in my ICS-Parser.

```
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (20170423T120000DESCRIPTION:Paulus mit Beat Müller\nKalender:Sonntagmorgen - [ws][predigt]Beat Müller / [bethel] / [notizen]Sunnestrahle, Rägetröpfli, XfürKids,X4Teens[/notizen][/ws]) at position 15 (D): The timezone could not be found in the database in /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php:494 Stack trace: #0 /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php(494): DateTime->__construct('20170423T120000...') #1 /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php(1112): ICal\ICal->iCalDateWithTimeZone(Array, 'DTEND') #2 /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php(259): ICal\ICal->processDateConversions() #3 /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php(137): ICal\ICal->initLines(Array) #4 /home/ht in /home/httpd/vhosts/chrischonazuerich.ch/httpdocs/wp/wp-content/plugins/calendar-sync/ICal.php on line 494
```

I have attached the ICS-File on which i refer.
On the server works PHP 7.0.11 with the following settings: http://chrischonazuerich.ch/srv-info/
I have also downloaded the newest version of the ICS-Parser from https://github.com/u01jmg3/ics-parser.

Do you see the point of error?
Thank you for your help and your answer.

[ChurchTools.ics.zip](https://github.com/u01jmg3/ics-parser/files/856064/ChurchTools.ics.zip)

**Comment by u01jmg3** [comment]
- This error is caused by an event description containing special characters - specifically the event that begins `Paulus mit Beat Müller...`
- This error lies with the data and not the parser
