### ISSUE TITLE
PHP 7.2 Warning - mb_split(): Pattern is not valid under UTF-8 encoding

### ISSUE THREAD

**Issue by garciagaston** [u01jmg3/ics-parser#230]
- PHP Version: `7.2.0`
- PHP date.timezone: `[Country]/[City]`
- ICS Parser Version: `v2.1.13`
- Linux

### Description of the Issue:
After switching to PHP 7.2, new \ICal\ICal($filename) causes PHP to throw the following 

```php
WARNING: mb_split(): Pattern is not valid under UTF-8 encoding #0 [internal function]
/vendor/johngrogg/ics-parser/src/ICal/ICal.php(2222)
```

### Steps to Reproduce:

- Use PHP 7.2. As soon as you try to load any `.ics`, it'll break.

[testCalendar.zip](https://github.com/u01jmg3/ics-parser/files/3461813/testCalendar.zip)

**Comment by u01jmg3** [comment]
Using the ICS provided on PHP 7.2.14 it works fine for me.

![PHP 7 2 14](https://user-images.githubusercontent.com/1266205/62387906-d7dcde00-b553-11e9-9064-4cf97e03a07e.png)

**Comment by garciagaston** [comment]
It's works well but throwing a lot of warning exceptions in the log file. 
mb_split(): Pattern is not valid under UTF-8 encoding

**Comment by u01jmg3** [comment]
> _throwing a lot of warning exceptions in the log file_

Which log file? In my PHP error log I see nothing.

Please provide me with the exact ICS file causing you the issue.

I cannot reproduce the issue you are seeing with the file you have already provided me.

**Comment by garciagaston** [comment]
I attached the ICS file and the warning logs on PHP 7.2.20
 
WEB.WARNING: mb_split(): Pattern is not valid under UTF-8 encoding #0 [internal function]: Logs\Handler\Error::handler(2, 'mb_split(): Pat...', 2222, Array) #1 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2222): mb_split('\x85', 'BEGIN:VCALENDAR') #2 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2266): ICal\ICal->mb_str_replace('\x85', Array, 'BEGIN:VCALENDAR') #3 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(329): ICal\ICal->cleanData('BEGIN:VCALENDAR') #4 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(255): ICal\ICal->initLines(Array)

WEB.WARNING: count(): Parameter must be an array or an object that implements Countable #0 [internal function]: Logs\Handler\Error::handler(2, 'count(): Parame...', 2223, Array) #1 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2223): count(false) #2 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2266): ICal\ICal->mb_str_replace('\x85', Array, 'BEGIN:VCALENDAR') #3 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(329): ICal\ICal->cleanData('BEGIN:VCALENDAR') #4 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(255): ICal\ICal->initLines(Array) 

WEB.WARNING: implode(): Invalid arguments passed #0 [internal function]: Logs\Handler\Error::handler(2, 'implode(): Inva...', 2224, Array) #1 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2224): implode(''', false) #2 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(2266): ICal\ICal->mb_str_replace('\x85', Array, 'BEGIN:VCALENDAR') #3 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(329): ICal\ICal->cleanData('BEGIN:VCALENDAR') #4 /vendor/johngrogg/ics-parser/src/ICal/ICal.php(255): ICal\ICal->initLines(Array)

**Comment by s0600204** [comment]
(The line numbers in the warnings appear to line up with the parser code as it was at v.`2.1.5`.)

I, too, cannot get the warnings to appear with php 7.2.x

**Comment by u01jmg3** [comment]
Closing due to inactivity. Please remember to try the latest version of the parser before raising an issue as the problem may already have been fixed.
